version: '3.7'

services:
  blog-db:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=my_db_user
      - POSTGRES_PASSWORD=passw0rd

volumes:
  user_db_data: {}
