POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "World3",
  "lastName": "Hello",
  "email": "test@gmail.com",
  "password": "password",
  "gender": "helicopter",
  "country": "country",
  "preferredCurrency": "eur"
}